### ISSUE TITLE
Doesn't work because dependency is deprecated

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-wireframe#2]
```
Uncaught Error: voxel-wireframe requires game-shell-voxel
```

**Comment by deathcap** [comment]
The error message in https://github.com/deathcap/voxel-wireframe/blob/622d69cfabeacff25699b358d0807a09621ef6c1/wire.js#L21 is wrong, https://github.com/deathcap/game-shell-voxel was the old side branch, it should say https://github.com/maxogden/voxel-engine/tree/ndarray (which corresponds to https://github.com/maxogden/voxel-engine/pull/103). But eventually I plan to release something like "voxel-engine-stackgl" from that branch so it can be more easily referenced.

**Comment by z3t0** [comment]
Okay that makes sense. As for releasing 'voxel-engine-stackgl' would be a great idea because I am also kind of confused at the moment of which one to use and how to use the *-stackgl version. Could you please explain some of the core differences? Aside from the three.js/stackgl. Also, does that mean your projects are based on the stackgl branch? Because I am currently using the older three.js and would like to follow what you are doing and eventually contribute. Thanks!

**Comment by deathcap** [comment]
@z3t0 yea I'm using only stackgl no three.js, new module is: https://github.com/voxel/voxel-engine-stackgl (derived from https://github.com/maxogden/voxel-engine but built on http://stack.gl/ instead of http://threejs.org/). The different graphics library is the fundamental difference, but there are many other changes that flow out of this major change (for example, rendering now uses https://github.com/voxel/voxel-mesher and https://github.com/voxel/voxel-shader). There's also an integrated plugin system https://github.com/voxel/voxel-plugins and some other enhancements to better support https://github.com/deathcap/voxelmetaverse
